// BEGIN: Extend jQuery
function addExpandedDesignText(a,b,c,d){jQuery(document).click("click touchend",a,function(a){a.preventDefault();
//var $this = jQuery(triggerSelector),
var e=jQuery(this).parent().parent();e.hasClass(b)?(e.removeClass(b),""!=c&&jQuery(this).html(c)):(
//jQuery("." + objClassName).removeClass(objClassName);
e.addClass(b),""!=d&&jQuery(this).html(d))})}function getParameterName(a){a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");var b=new RegExp("[\\?&]"+a+"=([^&#]*)"),c=b.exec(location.search);return null===c?"":decodeURIComponent(c[1].replace(/\+/g," "))}function addExpanded(a,b,c,d,e){jQuery(document).on("click touchend",a,function(a){var f=jQuery(this);e?f.addClass(b):f.hasClass(b)?f.removeClass(b):(d?jQuery("."+b).removeClass(b):f.removeClass(b),f.addClass(b),c&&f.hide())})}function addExpandedText(a,b,c,d,e,f,g){jQuery(b).click(function(h){h.preventDefault();var i=jQuery(a),j=jQuery(b);j.hasClass(c)?(j.removeClass(c),f&&i.slideToggle("fast"),""!=d&&j.html(d),g&&i.attr("data-attr-showhide","false")):(jQuery("."+c).removeClass(c),j.addClass(c),f&&i.slideToggle("fast"),""!=e&&j.html(e),g&&i.attr("data-attr-showhide","true"))})}var myData="1",strCounter=1,__window=jQuery(window),screenSize=__window.width();jQuery.extend({isDefined:function(a){return"undefined"!=typeof a},exists:function(a){return 0!==jQuery(a).length}}),jQuery.noConflict(),jQuery(document).ready(function(a){if(jQuery(".header__util-content").showHide({triggerSelector:".nav-support",contentSelector:".support-navigation",startClosed:!0,openedClass:"is-supportopen",closedClass:"is-supportclosed"}),jQuery(".header__util-content").showHide({triggerSelector:".nav-menu",contentSelector:".menu-navigation",startClosed:!0,openedClass:"is-menuopen",closedClass:"is-menuclosed"}),jQuery(".header__rightcols").showHide({triggerSelector:".search-item",contentSelector:".header__searchbox",startClosed:!0,openedClass:"is-searchopen",closedClass:"is-searchclosed"}),jQuery(".primary-navigation__item").showHide({triggerSelector:".primary-navigation__link",contentSelector:".primary-navigation__subitem",startClosed:!0,openedClass:"is-primaryNavopen",closedClass:"is-primaryNavClosed"}),jQuery(".faq-listing__item").showHide({triggerSelector:".faq-listing__group",contentSelector:".faq-listing__wrap",startClosed:!0,openedClass:"is-faqOpen",closedClass:"is-faqClosed",bodyClicked:!1}),jQuery(".browse-products__tabs").tabSelection({triggerSelector:".browse-products__item",contentSelector:".browse-products__segment",contentTabSelector:".browse-products__tabscontent",backButton:".back-btn",activeClass:"active",triggeredClass:"triggered",urlParamName:"tab",isMobileEnabled:!0}),jQuery(".where-buy__tabs").tabSelection({triggerSelector:".where-buy__item",contentSelector:".where-buy__segment",contentTabSelector:".where-buy__tabscontent",backButton:".back-btn",activeClass:"active",triggeredClass:"triggered",urlParamName:"tab",isMobileEnabled:!1}),
// truncate text
a(".browse-products__segment--teaser, .hover-content__teaser").each(function(b,c){var d=a(c),e=a.trim(d.text()),f=e.substr(0,150),g=f.split(" "),h=g.splice(0,g.length-1),i=h.join(" ");d.text(i+"...")}),jQuery.exists(".product-section")&&jQuery(".product-section").parent().addClass("product-container"),jQuery.exists(".gallery-thumbnail__listing")&&jQuery(".gallery-thumbnail__listing").galleryListing(),jQuery.exists(".product-comparelist")&&jQuery(".product-comparelist").compareProducts(),jQuery.exists(".product-comparelist__table")&&jQuery(".product-comparelist__table").compareProducts({isCompareTable:!0}),jQuery(".product-comparelist").showHide({triggerSelector:".product-comparelist__title",contentSelector:".product-comparelist__listing",startClosed:!0,openedClass:"open",closedClass:"closed",bodyClicked:!1}),jQuery.exists(".generic-listing")&&jQuery(".generic-listing").genericListing({isPaginationEnabled:!0,pageLimit:10}),jQuery.exists(".sales-reps__listing")&&jQuery(".sales-reps__listing").salesRepListing({isPaginationEnabled:!0,pageLimit:12}),jQuery.exists(".search-results__contentlisting")&&jQuery(".search-results__contentlisting").contentSearchListing({isPaginationEnabled:!0,pageLimit:10}),jQuery.exists("#productBrowseListing")&&jQuery("#productBrowseListing").productBrowse({isPaginationEnabled:!0,pageLimit:10,itemCount:".product-browse__itemcount"}),jQuery.exists(".hero-slider")||jQuery.exists(".page-banner")||jQuery("body").removeClass("header-static"),jQuery.exists("#txtLocationSearch"),
//Slider
jQuery.exists(".product-listing")&&jQuery(".product-listing").productSlider({isMobile:!0,killSlider:!0}),jQuery(".compare-back").click(function(a){a.preventDefault(),history.back(1)}),jQuery(".browse-products__segment--item").swipe({excludedElements:"button, input, select, textarea, .noSwipe",swipeLeft:function(a,b,c,d,e,f){jQuery(this).addClass("swiped-left").removeClass("swiped-right")},swipeRight:function(a,b,c,d,e,f){jQuery(this).addClass("swiped-right").removeClass("swiped-left")}}),jQuery("#txtWhereBuy").keydown(function(a){
// Allow: backspace, delete, tab, escape, enter and .
jQuery.inArray(a.keyCode,[46,8,9,27,13,110,190])!==-1||
// Allow: Ctrl+A
65==a.keyCode&&a.ctrlKey===!0||
// Allow: home, end, left, right, down, up
a.keyCode>=35&&a.keyCode<=40||
// Ensure that it is a number and stop the keypress
(a.shiftKey||a.keyCode<48||a.keyCode>57)&&(a.keyCode<96||a.keyCode>105)&&a.preventDefault()}),jQuery.exists(".product-gallery")&&jQuery(".product-gallery").productSlider({isMobile:!1,isPagerCustom:!0,adaptiveHeight:!1}),jQuery.exists(".collection-listing")&&0===jQuery(".section-content-wrapper").length&&jQuery(".collection-listing__heading").hide(),jQuery.exists(".hero-slider__container")&&jQuery(".hero-slider__container").heroSlider({swapBg:!0}),jQuery.exists(".collection-slider")&&jQuery(".collection-slider").heroSlider({swapBg:!1,duration:jQuery(".collection-slider[data-slider]").attr("data-duration"),startRandom:jQuery(".collection-slider[data-slider]").attr("data-start-random")}),jQuery.exists(".product-features")&&jQuery(".product-features").toggleContent({toggleMode:"height",showMoreObject:jQuery(".show-features"),showContainerHeight:190}),jQuery.exists(".product-links-wrapper")&&jQuery(".product-links-wrapper").toggleContent({toggleMode:"list",showMoreObject:jQuery(".show-downloads")}),jQuery.exists(".support-links-wrapper")&&jQuery(".support-links-wrapper").toggleContent({toggleMode:"list",showMoreObject:jQuery(".show-support-links")}),jQuery.exists(".frm__contactus")&&jQuery(".frm__contactus").contactUs(),jQuery.exists(".show-diagram")&&addExpanded(".show-diagram","expanded",!0,!0,!1),jQuery.exists(".shop-store__help")&&(addExpanded(".shop-store__help","expanded",!1,!1,!0),jQuery(document).on("click",".shop-store__close",function(a){a.preventDefault(),jQuery(this).parent().parent().find(".shop-store__help").removeClass("expanded")})),jQuery.exists(".shop-store")&&jQuery(".shop-store").storeShopping(),jQuery.exists(".product-details__pricing")&&jQuery("body").productDetails(),jQuery.exists(".product-smart-listing")&&(1==jQuery(".product-smart-listing > a").length?jQuery(".product-smart-listing > a").addClass("disabled"):jQuery(".product-smart-listing > a").removeClass("disabled"),jQuery(".product-smart-listing > a").click(function(){if(jQuery(".product-smart-listing > a").length>1){var a=jQuery(this).attr("data-tab");jQuery(".product-smart-listing > a").removeClass("active"),jQuery(".tab-content").removeClass("active"),jQuery(this).addClass("active"),jQuery(".tab-content-wrapper").find("[data-tab='"+a+"']").addClass("active")}})),jQuery.exists(".catalog-finishes"),
//equalize the row height for icon listing
a(".icon-listing__item .icon-listing__link").matchHeight(),
// equalize design studio row heights
a(".design-option__row-zero").matchHeight(),a(".design-option__row-one").matchHeight(),a(".design-option__row-two").matchHeight(),a(".design-option__row-three").matchHeight(),a(".design-option__row-four").matchHeight(),a(".design-option__row-five").matchHeight(),
// launch videos in a modal
a(".video-modal").magnificPopup({disableOn:700,type:"iframe",mainClass:"mfp-fade",removalDelay:160,preloader:!1,fixedContentPos:!1}),jQuery.exists(".design-option__heading--mobile")){var b=jQuery(".design-option__heading--mobile").data("show-text"),c=jQuery(".design-option__heading--mobile").data("hide-text");addExpandedDesignText(".design-option__heading--mobile","expanded",b,c)}
//Swapping the two image sources
var d=function(){var a=jQuery(this).find("img"),b=a.data("hover-src");""!==b&&void 0!==b&&(a.data("hover-src",a.attr("src")),a.attr("src",b))};jQuery(".icon-listing__link").hover(d,d),jQuery(".footer__socialmedia--links > a").hover(d,d)});
//# sourceMappingURL=symmons_011.js.map