var Symmons=Symmons||{};!function($){"use strict";jQuery.fn.genericListing=function(a){return this.each(function(){var b=Object.create(Symmons.genericListing);b.init(this,a)})},
//Options
jQuery.fn.genericListing.options={contentSelector:".generic-listing",templateSelector:"#template-genericListing",urlSelector:jQuery(".generic-listing").attr("data-ajax-url"),totalRecords:"",totalPages:"",isPaginationEnabled:!1,paginationObj:jQuery(".pagination-content")},
//Gallery Listing
Symmons.genericListing={init:function(a,b){var c=this;jQuery(".no-records-found").hide(),c.$container=jQuery(a),c.options=jQuery.extend({},jQuery.fn.genericListing.options,b),$loading.show(),c.options.isPaginationEnabled&&(c.options.urlSelector=c.options.urlSelector+"?pageNum=1"),c.makeAjaxCall()},bindElements:function(){},bindHandlers:function(){},makeAjaxCall:function(){var a=this;
// Make the AJAX call
jQuery.ajax({url:a.options.urlSelector,type:"GET",cache:!0,contentType:"application/json; charset=utf-8",dataType:"json",async:!0,error:function(a){console.log("Error"+a.responseText)},success:function(b){a.options.totalRecords=jQuery(b)[0].TotalRecordCount,a.options.totalPages=jQuery(b)[0].TotalPagesCount,a.options.totalRecords>0?(a.bindgenericListing(b),a.options.isPaginationEnabled&&(a.bindPagination(),jQuery(a.options.contentSelector).data("paginate").refresh(1,a.options.totalPages)),a.bindElements(),a.bindHandlers()):(jQuery(a.options.noRecords).show(),jQuery(".no-records-found").show(),jQuery(a.options.contentSelector).hide(),a.options.isPaginationEnabled&&a.options.paginationObj.hide(),$loading.hide())}})},bindPagination:function(){var a=this;a.options.isPaginationEnabled&&("1"==a.options.totalPages?a.options.paginationObj.hide():a.options.paginationObj.show()),jQuery(a.options.contentSelector).paginate({onSuccess:function(b){jQuery(a.options.contentSelector).html(""),a.bindgenericListing(b)}})},bindgenericListing:function(data){var self=this,$container=jQuery(self.options.templateSelector),$theTemplate=Handlebars.compile($container.html());jQuery(self.options.contentSelector).append($theTemplate(eval(data))),
//self.loadListing(data);
$loading.hide()}}}(jQuery);
//# sourceMappingURL=symmons_002.js.map