var Symmons=Symmons||{},myDatas={};!function($){"use strict";jQuery.fn.galleryListing=function(a){return this.each(function(){var b=Object.create(Symmons.galleryListing);b.init(this,a)})},
//Options
jQuery.fn.galleryListing.options={contentSelector:".gallery-thumbnail__listing",templateSelector:"#template-Thumbnaillisting",urlSelector:jQuery(".gallery-thumbnail__listing").attr("data-ajax-url"),featuredContentSelector:".featured-video__content",featuredFrameSelector:"featured-video__frame",featuredTitle:".featured-video__title",featuredTeaser:".featured-video__teaser",videoListSelector:".gallery-thumbnail__teaser",youtubeURL:" http://www.youtube.com/embed/",youtubeAutohide:1,youtubeShowinfo:0,youtubeAllowfullscreen:!0,featuredImageSelector:"featuredImagePlaceholder"},
//Gallery Listing
Symmons.galleryListing={init:function(a,b){var c=this;jQuery(".no-records-found").hide(),c.$container=jQuery(a),c.options=jQuery.extend({},jQuery.fn.galleryListing.options,b),$loading.show(),c.makeAjaxCall()},bindElements:function(){var a=this;a.$videoTrigger=a.$container.find(a.options.videoListSelector)},bindHandlers:function(){var a=this;a.$videoTrigger.bind("click",function(b){b.preventDefault(),a.loadCurrentVideoOnClick(this)}),jQuery(window).resize(function(){a.bindPinVideo()})},loadCurrentVideoOnClick:function(a){var b=this,c=jQuery(a),d=c.next().next().find(".gallery-thumbnail__content-title").html(),e=c.find("img").data("video-url"),f=c.next().next().find(".gallery-thumbnail__content-teaser").html(),g=c.find("img").data("image-url");void 0!=d&&""!=d?(jQuery(b.options.featuredTitle).show(),jQuery(b.options.featuredTitle).html(d)):jQuery(b.options.featuredTitle).hide(),"video"==c.parent().data("content-type")?(jQuery("#"+b.options.featuredImageSelector).hide(),jQuery("#"+b.options.featuredFrameSelector).show(),jQuery("#"+b.options.featuredFrameSelector).attr("src",b.options.youtubeURL+e+"?rel=0&autohide="+b.options.youtubeAutohide+"&showinfo="+b.options.youtubeShowinfo)):Modernizr.mq(Symmons.Settings.MediaQueries.BelowTablet)?(window.open(g,"_blank"),
//window.location.href = strImageURL;
jQuery(b.options.featuredTitle).hide()):(jQuery("#"+b.options.featuredFrameSelector).hide(),jQuery("#"+b.options.featuredImageSelector).show(),jQuery("#"+b.options.featuredFrameSelector).attr("src",""),jQuery("#"+b.options.featuredImageSelector).find("img").attr("src",g)),void 0!=f&&""!=f?jQuery(b.options.featuredTeaser).html(f):jQuery(b.options.featuredTeaser).hide()},makeAjaxCall:function(){var a=this;
// Make the AJAX call
jQuery.ajax({url:a.options.urlSelector,type:"GET",cache:!0,contentType:"application/json; charset=utf-8",dataType:"json",async:!0,error:function(a){console.log("Error"+a.responseText)},success:function(b){a.bindGalleryListing(b),a.bindElements(),a.bindHandlers(),a.bindPinVideo()}})},bindPinVideo:function(){jQuery(".featured-video__content").removeAttr("style",""),jQuery(".pinned").pin({containerSelector:".featured-video__two-cols",minWidth:767})},bindGalleryListing:function(data){var self=this,$container=jQuery(self.options.templateSelector),$theTemplate=Handlebars.compile($container.html());jQuery(self.options.contentSelector).append($theTemplate(eval(data))),self.loadFeaturedVideo(data)},loadFeaturedVideo:function(a){var b=this,c="",d=0;jQuery.each(jQuery(a)[0].MasterListingData,function(a,e){if("video"===e.ListingType)return d=1,""!=e.ListingTitle?jQuery(b.options.featuredTitle).html(e.ListingTitle):jQuery(b.options.featuredTitle).hide(),""!=e.ListingVideoUrl&&(c+=b.options.youtubeAllowfullscreen?'<iframe src="'+b.options.youtubeURL+e.ListingVideoUrl+"?rel=0&autohide="+b.options.youtubeAutohide+"&showinfo="+b.options.youtubeShowinfo+'" class="'+b.options.featuredFrameSelector+'" id="'+b.options.featuredFrameSelector+'" frameborder="0" allowfullscreen></iframe><figure class="featured-video__image" id="featuredImagePlaceholder"><img src="" alt="" /></figure>':'<iframe src="'+b.options.youtubeURL+e.ListingVideoUrl+"?rel=0&autohide="+b.options.youtubeAutohide+"&showinfo="+b.options.youtubeShowinfo+'" id="'+b.options.featuredFrameSelector+'" frameborder="0"></iframe>'),""!=e.ListingTeaserDesc&&(c+='<p class="featured-video__teaser">'+e.ListingTeaserDesc+"</p>"),!1}),
//No Featured Video Exists
0==d&&jQuery(".no-records-found").show(),
//Finally appending the template
jQuery(b.options.featuredContentSelector).append(c),$loading.hide()}}}(jQuery);
//# sourceMappingURL=symmons_007.js.map